export const data = [
  {
    id: 1,
    question: "Vue or next?",
    user: "Chester",
    uploaded: new Date(),
    upvote: 4,
    downvote: 9,
  },
  {
    id: 2,
    question: "JS or TS ",
    user: "Raymond",
    uploaded: new Date(),
    upvote: 0,
    downvote: 4,
  },
  {
    id: 3,
    question: "Rust or golang",
    user: "Vix",
    uploaded: new Date(),
    upvote: 3,
    downvote: 5,
  },
  {
    id: 1,
    question: "Vue or next?",
    user: "Chester",
    uploaded: new Date(),
    upvote: 4,
    downvote: 9,
  },
  {
    id: 2,
    question: "JS or TS ",
    user: "Raymond",
    uploaded: new Date(),
    upvote: 0,
    downvote: 4,
  },
  {
    id: 3,
    question: "Rust or golang",
    user: "Vix",
    uploaded: new Date(),
    upvote: 3,
    downvote: 5,
  },
  {
    id: 1,
    question: "Vue or next?",
    user: "Chester",
    uploaded: new Date(),
    upvote: 4,
    downvote: 9,
  },
  {
    id: 2,
    question: "JS or TS ",
    user: "Raymond",
    uploaded: new Date(),
    upvote: 0,
    downvote: 4,
  },
  {
    id: 3,
    question: "Rust or golang",
    user: "Vix",
    uploaded: new Date(),
    upvote: 3,
    downvote: 5,
  },
  {
    id: 1,
    question: "Vue or next?",
    user: "Chester",
    uploaded: new Date(),
    upvote: 4,
    downvote: 9,
  },
  {
    id: 2,
    question: "JS or TS ",
    user: "Raymond",
    uploaded: new Date(),
    upvote: 0,
    downvote: 4,
  },
  {
    id: 3,
    question: "Rust or golang",
    user: "Vix",
    uploaded: new Date(),
    upvote: 3,
    downvote: 5,
  },
  {
    id: 1,
    question: "Vue or next?",
    user: "Chester",
    uploaded: new Date(),
    upvote: 4,
    downvote: 9,
  },
  {
    id: 2,
    question: "JS or TS ",
    user: "Raymond",
    uploaded: new Date(),
    upvote: 0,
    downvote: 4,
  },
  {
    id: 3,
    question: "Rust or golang",
    user: "Vix",
    uploaded: new Date(),
    upvote: 3,
    downvote: 5,
  },
  {
    id: 1,
    question: "Vue or next?",
    user: "Chester",
    uploaded: new Date(),
    upvote: 4,
    downvote: 9,
  },
  {
    id: 2,
    question: "JS or TS ",
    user: "Raymond",
    uploaded: new Date(),
    upvote: 0,
    downvote: 4,
  },
  {
    id: 3,
    question: "Rust or golang",
    user: "Vix",
    uploaded: new Date(),
    upvote: 3,
    downvote: 5,
  },
  {
    id: 1,
    question: "Vue or next?",
    user: "Chester",
    uploaded: new Date(),
    upvote: 4,
    downvote: 9,
  },
  {
    id: 2,
    question: "JS or TS ",
    user: "Raymond",
    uploaded: new Date(),
    upvote: 0,
    downvote: 4,
  },
  {
    id: 3,
    question: "Rust or golang",
    user: "Vix",
    uploaded: new Date(),
    upvote: 3,
    downvote: 5,
  },
  {
    id: 1,
    question: "asdfasdf or next?",
    user: "Chester",
    uploaded: new Date(),
    upvote: 4,
    downvote: 9,
  },
  {
    id: 2,
    question: "adsfadsf or TS ",
    user: "Raymond",
    uploaded: new Date(),
    upvote: 0,
    downvote: 4,
  },
  {
    id: 3,
    question: "Rust or golang",
    user: "Vix",
    uploaded: new Date(),
    upvote: 3,
    downvote: 5,
  },
  {
    id: 1,
    question: "Vue or next?",
    user: "Chester",
    uploaded: new Date(),
    upvote: 4,
    downvote: 9,
  },
  {
    id: 2,
    question: "JS or TS ",
    user: "Raymond",
    uploaded: new Date(),
    upvote: 0,
    downvote: 4,
  },
  {
    id: 3,
    question: "asdfasdfgrgrtgrg or golang",
    user: "Vix",
    uploaded: new Date(),
    upvote: 3,
    downvote: 5,
  },
  {
    id: 1,
    question: "asdfasdf or next?",
    user: "Chester",
    uploaded: new Date(),
    upvote: 4,
    downvote: 9,
  },
  {
    id: 2,
    question: "ftyjftjytf or TS ",
    user: "Raymond",
    uploaded: new Date(),
    upvote: 0,
    downvote: 4,
  },
  {
    id: 3,
    question: "Rfjftuyjtyfjust or golang",
    user: "Vix",
    uploaded: new Date(),
    upvote: 3,
    downvote: 5,
  },
];
